---
development:
  dialect: postgres
  database: oauth-dev
  user: postgres
  password: postgres
  host: db
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@db:5432/oauth-test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/oauth-service-v1_production?sslmode=disable"}}
