version: '3.8'
services:
  devcontainer:
    #image: gobuffalo/buffalo:v0.18.13
    build: .
    volumes:
      - ../..:/workspaces:cached
    network_mode: service:db
    command: sleep infinity

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: oauth-dev
      PORT: 5432

volumes:
  postgres-data:
